### ISSUE TITLE
Setting headers after res is sent

### ISSUE THREAD

**Issue by clayrisser** [abersager/redux-persist-cookie-storage#14]
I get the following error from the server. I can't figure out why it's setting headers after I send the response. I'm creating my store long before I send back a response.

```
_http_outgoing.js:491
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at Cookies.set (webpack-internal:///./node_modules/cookies/index.js:115:13)
    at NodeCookiesWrapper.set (webpack-internal:///./node_modules/redux-persist-cookie-storage/src/node-cookies-wrapper.js:26:16)
    at CookieStorage.setItem (webpack-internal:///./node_modules/redux-persist-cookie-storage/src/redux-persist-cookie-storage.js:35:16)
    at writeStagedState (webpack-internal:///./node_modules/redux-persist/es/createPersistoid.js:88:28)
    at Timeout.processNextKey [as _onTimeout] (webpack-internal:///./node_modules/redux-persist/es/createPersistoid.js:76:7)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

```

The error is coming from line 25 in the `node-cookies-wrapper.js` file

```js
// . . .
NodeCookiesWrapper.prototype.set = function(key, value, options) {
  key = encodeKey(key);
  value = (value + '').replace(/[^!#$&-+\--:<-\[\]-~]/g, encodeURIComponent);
  this.cookies.set(key, value, options);
};
// . . .
```

**Comment by clayrisser** [comment]
I fixed it. I wasn't waiting for persistStore to finish, and I wasn't flushing the persistor before sending the response.

`persistor.flush()` :+1:
